---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ong-donation-webapi
  namespace: ong-donation
  labels:
    app: ong-donation-webapi
    app.kubernetes.io/name: ong-donation-webapi
    app.kubernetes.io/part-of: ong-donation-platform

---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: ong-donation-identity
  namespace: ong-donation
  labels:
    app: ong-donation-webapi
spec:
  type: 0  # MSI
  resourceID: /subscriptions/{SUBSCRIPTION_ID}/resourcegroups/{RESOURCE_GROUP}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ong-donation-aks-identity-p
  clientID: {CLIENT_ID}

---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: ong-donation-binding
  namespace: ong-donation
spec:
  azureIdentity: ong-donation-identity
  selector: ong-donation-selector

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ong-donation-keyvault-secrets
  namespace: ong-donation
  labels:
    app: ong-donation-webapi
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: "{CLIENT_ID}"
    keyvaultName: "ong-donation-kv-p"
    cloudEnvAzurePublicCloud: "true"
    tenantId: "{TENANT_ID}"
    objects: |
      array:
        - |
          objectName: db-connection-string
          objectType: secret
          objectAlias: DB_CONNECTION_STRING
        - |
          objectName: jwt-key
          objectType: secret
          objectAlias: JWT_KEY
        - |
          objectName: rabbitmq-connection-string
          objectType: secret
          objectAlias: RABBITMQ_CONNECTION_STRING
        - |
          objectName: service-bus-connection-string
          objectType: secret
          objectAlias: SERVICE_BUS_CONNECTION_STRING
        - |
          objectName: appinsights-connection-string
          objectType: secret
          objectAlias: APPINSIGHTS_CONNECTION_STRING
  secretObjects:
  - secretKey: db-connection-string
    objectName: db-connection-string
    data: true
  - secretKey: jwt-key
    objectName: jwt-key
    data: true
  - secretKey: rabbitmq-connection-string
    objectName: rabbitmq-connection-string
    data: true
  - secretKey: service-bus-connection-string
    objectName: service-bus-connection-string
    data: true
  - secretKey: appinsights-connection-string
    objectName: appinsights-connection-string
    data: true
