---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ong-donation-webapi
  namespace: ong-donation
  labels:
    app: ong-donation-webapi
    app.kubernetes.io/name: ong-donation-webapi
    app.kubernetes.io/part-of: ong-donation-platform
  annotations:
    azure.workload.identity/client-id: "${CLIENT_ID}"

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ong-donation-keyvault-secrets
  namespace: ong-donation
  labels:
    app: ong-donation-webapi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "${CLIENT_ID}"
    keyvaultName: "ong-donation-kv-p-v4"
    tenantId: "${TENANT_ID}"
    objects: |
      array:
        - |
          objectName: db-connection-string
          objectType: secret
        - |
          objectName: jwt-key
          objectType: secret
        - |
          objectName: rabbitmq-connection-string
          objectType: secret
        - |
          objectName: service-bus-connection-string
          objectType: secret
        - |
          objectName: appinsights-connection-string
          objectType: secret
  secretObjects:
  - secretName: ong-donation-secrets
    type: Opaque
    data:
    - objectName: db-connection-string
      key: ConnectionStrings__DefaultConnection
    - objectName: jwt-key
      key: Jwt__Key
    - objectName: rabbitmq-connection-string
      key: RabbitMQ__ConnectionString
    - objectName: service-bus-connection-string
      key: ServiceBus__ConnectionString
    - objectName: appinsights-connection-string
      key: ApplicationInsights__ConnectionString
